"""
Alert model - generated by detection / correlation engines.
"""
import enum
from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, DateTime, Text, Enum, Float, ForeignKey, Boolean,
    Index,
)
from sqlalchemy.orm import relationship
from threatloom.database import Base


class AlertSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ESCALATED = "ESCALATED"


class Alert(Base):
    """Security alert raised by detection engine."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Identification
    alert_uid = Column(String(64), unique=True, nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)

    # Classification
    severity = Column(Enum(AlertSeverity), nullable=False, index=True)
    status = Column(Enum(AlertStatus), nullable=False, default=AlertStatus.NEW, index=True)
    confidence = Column(Float, nullable=True)   # 0.0 - 1.0

    # Source
    detection_source = Column(String(64), nullable=False)    # rule, behavioral, correlation
    rule_id = Column(String(128), nullable=True)
    attack_type = Column(String(64), nullable=True)

    # Affected entities
    src_ip = Column(String(45), nullable=True, index=True)
    dst_ip = Column(String(45), nullable=True)
    http_path = Column(Text, nullable=True)
    session_id = Column(String(64), nullable=True)

    # GeoIP
    geo_country = Column(String(2), nullable=True)

    # MITRE ATT&CK
    mitre_tactic = Column(String(64), nullable=True)
    mitre_technique = Column(String(64), nullable=True)

    # Correlation
    correlated_log_ids = Column(Text, nullable=True)   # JSON array of log IDs
    event_count = Column(Integer, default=1)

    # Timestamps
    first_seen = Column(DateTime, nullable=False, default=datetime.utcnow)
    last_seen = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)

    # Triage
    assigned_to = Column(Integer, ForeignKey("users.id"), nullable=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"), nullable=True)

    # Response
    auto_response_taken = Column(Boolean, default=False)
    response_action = Column(String(64), nullable=True)

    # Relations
    incident = relationship("Incident", back_populates="alerts")

    __table_args__ = (
        Index("ix_alerts_severity_status", "severity", "status"),
        Index("ix_alerts_created", "created_at"),
    )

    def __repr__(self):
        return f"<Alert id={self.id} title={self.title} severity={self.severity}>"
